name: build-test-deploy
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install --silly
      - run: npm run build --silly
  test: 
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install --silly
      - name: Install dependencies
        run: npm install --save-dev eslint
      - name: Run tests
        run: npm test --silly -- --fix
  deploy:
    needs: test

    permissions:
      contents: write
      pages: write     
      id-token: write  

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: configure github pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next

      - run: npm install
      - run: npm run build

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: pages
          path: "./out"

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          
# Here's what happens when using peaceiris/actions-gh-pages@v3 instead of :

#     The action checks out the repository and sets up the environment.
#     It builds the project using the npm run build command.
#     It deploys the built files to GitHub Pages using the github_token and publish_dir inputs.

# By using peaceiris/actions-gh-pages@v3, we avoided the need to upload an artifact separately, which was causing 
# the issue. Instead, the action handles the deployment process internally, making it a more reliable and efficient 
# way to deploy to GitHub Pages.

# Additionally, peaceiris/actions-gh-pages@v3 is a well-maintained and widely-used action, which means it's less 
# likely to have issues or bugs compared to other actions.

# Overall, using peaceiris/actions-gh-pages@v3 simplified the deployment process and avoided the artifact upload 
# issue, resulting in a successful deployment to GitHub Pages.
